name: Build FLIP Fluids for Windows

on:
  workflow_run:
    workflows: ["trigger"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-lz4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python packages
      run: pip install -r requirements.txt

    - name: Clone FLIP Fluids repository
      shell: msys2 {0}
      run: git clone https://github.com/rlguy/Blender-FLIP-Fluids.git

    - name: Build FLIP Fluids with verbose logging
      id: build_flip_fluids
      shell: msys2 {0}
      run: |
        cd Blender-FLIP-Fluids
        export VERBOSE=1
        python build.py 2>&1 | tee build.log
        echo "exit_code=$?" >> $GITHUB_OUTPUT
      continue-on-error: true

    - name: Upload build logs on failure
      if: ${{ steps.build_flip_fluids.outputs.exit_code != 0 }}
      uses: actions/upload-artifact@v4
      with:
        name: build-failure-logs
        path: |
          Blender-FLIP-Fluids/build.log
          Blender-FLIP-Fluids/CMakeCache.txt
          Blender-FLIP-Fluids/CMakeFiles/CMakeOutput.log
          Blender-FLIP-Fluids/CMakeFiles/CMakeError.log

    - name: Fail if build unsuccessful
      if: ${{ steps.build_flip_fluids.outputs.exit_code != 0 }}
      run: exit 1

    - name: Extract version info
      if: ${{ steps.build_flip_fluids.outputs.exit_code == 0 }}
      shell: bash
      run: |
        cd Blender-FLIP-Fluids
        version=$(grep -oP 'FLIP Fluids version \K[\d\.]+' build.log | head -1)
        echo "FLIP_FLUIDS_VERSION=$version" >> $GITHUB_ENV
        echo "Version: $version"

    - name: Package addon
      if: ${{ steps.build_flip_fluids.outputs.exit_code == 0 }}
      shell: pwsh
      run: |
        $source = './Blender-FLIP-Fluids/build/bl_flip_fluids/flip_fluids_addon'
        $dest = './Blender-FLIP-Fluids/build/flip_fluids_addon.zip'
        if (Test-Path $source) {
          Compress-Archive -Path $source -DestinationPath $dest -Force
        } else {
          Write-Error "Addon directory missing: $source"
          exit 1
        }

    - name: Upload artifact
      if: ${{ steps.build_flip_fluids.outputs.exit_code == 0 }}
      uses: actions/upload-artifact@v4
      with:
        name: flip-fluids-addon
        path: Blender-FLIP-Fluids/build/flip_fluids_addon.zip

    - name: Create release
      if: ${{ success() && (github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch') }}
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.FLIP_FLUIDS_VERSION }}
        name: "FLIP Fluids ${{ env.FLIP_FLUIDS_VERSION }}"
        files: Blender-FLIP-Fluids/build/flip_fluids_addon.zip
