name: Check for New Version in Commit Messages

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight to reduce API calls

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Fetch Tags
        run: |
          git fetch --tags

      - name: Get Latest Tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: ${LATEST_TAG}"
          echo "latest_tag=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Extract Current Version from Commit Message
        id: extract_version
        run: |
          VERSION_PATTERN="Version ([0-9]+)\.([0-9]+)\.([0-9]+)"
          LATEST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ "${LATEST_COMMIT_MESSAGE}" =~ $VERSION_PATTERN ]]; then
            CURRENT_VERSION="${BASH_REMATCH[0]}"
            echo "Detected new version: ${CURRENT_VERSION}"
            echo "current_version=${CURRENT_VERSION}" >> $GITHUB_ENV
          else
            echo "No version information found in the latest commit message."
            echo "current_version=none" >> $GITHUB_ENV
          fi

      - name: Check if the version has changed
        id: check_if_changed
        run: |
          if [[ "${{ env.current_version }}" != "none" && "${{ env.current_version }}" != "${{ env.latest_tag }}" ]]; then
            echo "New version detected: ${CURRENT_VERSION}. Triggering the build."
            echo "trigger_build=true" >> $GITHUB_ENV
          else
            echo "No new version found or no version information available."
            echo "trigger_build=false" >> $GITHUB_ENV
          fi
      
      - name: Trigger Build Workflow
        if: env.trigger_build == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/GhostYiL/Flip-Fluids-Compiler/actions/workflows/build_flip_fluids.yml/dispatches \
            -d '{"ref":"main"}'
