name: trigger

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Prepare
        run: sudo apt-get install dos2unix
      
      - name: Dos
        run: dos2unix isUpdated.sh

      - name: +Exec
        run: chmod +x ./isUpdated.sh
        
      - name: Run sh
        run: ./isUpdated.sh
