name: trigger

on:
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make script executable
        run: chmod +x ./isUpdated.sh
      - name: Run isUpdated.sh
        run: ./isUpdated.sh
